<?php

namespace SysadminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function updateStatus() {
        
    }

    public function listAll() {
        $dql = 'SELECT u FROM SysadminBundle:User u';
        $users = $this->getEntityManager()->createQuery($dql);

        return $users->getResult();
    }
}
