<?php

namespace SysadminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    public function updateStatus($users) {
        $whereY = [];
        $whereN = [];
        foreach ($users as $user) {
            $u = $this->find((int) $user);
            if ($u->getActive() == 'Y') {
                $whereN[] = (int) $user;
            } else {
                $whereY[] = (int) $user;
            }
        }
        if (!empty($whereN)) {
            try {
                $dql = "UPDATE SysadminBundle:User u SET u.active = 'N' WHERE u.id IN (" . implode(',', $whereN) . ")";
                $this->getEntityManager()->createQuery($dql)->getResult();
            } catch (Exception $e) {
                return false;
            }
        }
        if (!empty($whereY)) {
            try {
                $dql = "UPDATE SysadminBundle:User u SET u.active = 'Y' WHERE u.id IN (" . implode(',', $whereY) . ")";
                $this->getEntityManager()->createQuery($dql)->getResult();
            } catch (Exception $e) {
                return false;
            }
        }
        return true;
    }

    public function insert($user) {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();

        return $user;
    }

    public function update() {
        
    }

    public function listAll() {
        $dql = 'SELECT u FROM SysadminBundle:User u';
        $users = $this->getEntityManager()->createQuery($dql);

        return $users->getResult();
    }

}
